[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "coreforge"
version = "0.0.1"
authors = [
  { name="Cole Gentry", email="cole.gentry@austin.utexas.edu" },
]
description = "A collection of Python tools for setting up Nuclear Reactor Models"
readme = "README.md"
keywords = []
requires-python = ">=3.10"
license = {text = "BSD-3-Clause"}
classifiers = [
    'Development Status :: 3 - Alpha',
    'License :: OSI Approved :: BSD-3-Clause',
    'Programming Language :: Python :: 3',
    'Operating System :: OS Independent',
]
dependencies = [
    "numpy>=1.24.0",
    "openmc>=0.14.0",
    "MPACTPy>=0.0.1"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pylint",
    "black",
]
test = [
    "pytest",
    "pylint",
]

[project.urls]
Homepage = "https://github.com/UT-Computational-NE/CoreForge"
Issues = "https://github.com/UT-Computational-NE/CoreForge/issues"

[tool.pylint.'messages control']
disable = [
    "chained-comparison",
    "broad-exception-raised",
    "broad-exception-caught",
    "dangerous-default-value",
    "duplicate-code",
    "eval-used",
    "fixme",
    "invalid-name",
    "missing-module-docstring",
    "missing-function-docstring",
    "pointless-string-statement",
    "redefined-outer-name",
    "too-few-public-methods",
    "too-many-lines",
    "too-many-locals",
    "too-many-branches",
    "too-many-ancestors",
    "too-many-arguments",
    "too-many-statements",
    "too-many-nested-blocks",
    "too-many-instance-attributes",
    "too-many-positional-arguments",
    "unspecified-encoding",
    "unused-variable"
]

[tool.pylint.'format']
max-line-length = 127

[tool.black]
line-length = 127